[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js blog sayfaları için yönlendirme
[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat/index.html"
  status = 200

# Ana yönlendirme
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 